// Demo courses data (used as fallback when DB is empty or unavailable)
export const DEMO_COURSES = [
  {
    id: 'demo-1',
    title: 'Spring Boot Microservices — Zero to Production',
    slug: 'springboot-microservices',
    description: 'Build production-grade microservices with Spring Boot, REST APIs, PostgreSQL, Docker, and deploy on AWS. Covers CQRS, event-driven patterns, and CI/CD.',
    price_inr: 3999,
    content_url: 'https://example.com/course1',
    thumbnail_color: 'from-emerald-500 to-green-700',
    lessons: ['Spring Boot Fundamentals', 'REST API Design', 'Database Design (PostgreSQL)', 'Microservices Architecture', 'Docker & Kubernetes', 'CI/CD Pipeline', 'AWS Deployment', 'Monitoring & Logging'],
    is_published: true,
  },
  {
    id: 'demo-2',
    title: 'Android App Development — Zero to Hero',
    slug: 'android-zero-to-hero',
    description: 'Complete Android development course. Learn Java, XML, Firebase, Material Design, and publish your first app on Play Store.',
    price_inr: 2999,
    content_url: 'https://example.com/course2',
    thumbnail_color: 'from-violet-500 to-purple-700',
    lessons: ['Android Studio Setup', 'Java Fundamentals', 'XML Layouts & Views', 'Activities & Intents', 'RecyclerView & Adapters', 'Firebase Integration', 'REST API Calls', 'Play Store Publishing'],
    is_published: true,
  },
  {
    id: 'demo-3',
    title: 'REST API Design & Best Practices',
    slug: 'rest-api-design',
    description: 'Master RESTful API design patterns, versioning, pagination, error handling, authentication, and documentation with Swagger/OpenAPI.',
    price_inr: 1999,
    content_url: 'https://example.com/course3',
    thumbnail_color: 'from-blue-500 to-indigo-700',
    lessons: ['REST Principles & HTTP Methods', 'Resource Naming & URIs', 'Request/Response Design', 'Pagination & Filtering', 'Error Handling Patterns', 'JWT Authentication', 'Swagger/OpenAPI Docs', 'Rate Limiting & Security'],
    is_published: true,
  },
  {
    id: 'demo-4',
    title: 'Kafka & Event-Driven Architecture',
    slug: 'kafka-event-driven',
    description: 'Learn Apache Kafka from scratch: producers, consumers, topics, partitions, and how to build event-driven microservices with Spring Boot.',
    price_inr: 2499,
    content_url: 'https://example.com/course4',
    thumbnail_color: 'from-amber-500 to-orange-700',
    lessons: ['Kafka Architecture', 'Producers & Consumers', 'Topics & Partitions', 'Spring Kafka Integration', 'Event Sourcing Basics', 'CQRS Pattern', 'Error Handling & DLQ', 'Production Deployment'],
    is_published: true,
  },
  {
    id: 'demo-5',
    title: 'Play Store Publishing & ASO Guide',
    slug: 'playstore-aso-guide',
    description: 'Publish your Android app and optimize for visibility. Covers Play Console, keyword research, screenshot design, and monetization.',
    price_inr: 999,
    content_url: 'https://example.com/course5',
    thumbnail_color: 'from-pink-500 to-rose-700',
    lessons: ['Play Console Setup', 'App Listing Optimization', 'Keyword Research', 'Screenshot & Banner Design', 'Monetization Strategies', 'Review Management'],
    is_published: true,
  },
  {
    id: 'demo-6',
    title: 'Docker & Kubernetes for Java Developers',
    slug: 'docker-kubernetes-java',
    description: 'Containerize your Spring Boot apps and deploy to Kubernetes. Covers Docker, Docker Compose, K8s pods, services, deployments, and Helm.',
    price_inr: 2999,
    content_url: 'https://example.com/course6',
    thumbnail_color: 'from-cyan-500 to-blue-700',
    lessons: ['Docker Fundamentals', 'Dockerizing Spring Boot', 'Docker Compose', 'Kubernetes Architecture', 'Pods, Services & Deployments', 'Helm Charts', 'CI/CD with K8s', 'Cloud Deployment'],
    is_published: true,
  },
];

// Demo services data — specialized consultation plans
export const DEMO_SERVICES = [
  {
    id: 'demo-s1',
    title: 'Android Dev Call',
    slug: 'android-consultation',
    description: 'Quick Android development consultation — app idea validation, architecture, and Play Store tips',
    price_inr: 799,
    duration_min: 30,
    duration: '30 min',
    category: 'Mobile',
    popular: false,
    features: ['App idea validation', 'Architecture advice', 'Play Store publishing tips', 'Firebase integration help', 'Email follow-up'],
  },
  {
    id: 'demo-s2',
    title: 'Spring Boot Deep Dive',
    slug: 'springboot-consultation',
    description: 'In-depth Spring Boot & microservices consultation with code review',
    price_inr: 1499,
    duration_min: 45,
    duration: '45 min',
    category: 'Backend',
    popular: true,
    features: ['Microservices architecture review', 'REST API design patterns', 'Database schema review', 'JMS / Kafka setup advice', 'Code review + best practices', 'Slack follow-up'],
  },
  {
    id: 'demo-s3',
    title: 'API & Microservices Plan',
    slug: 'api-microservices',
    description: 'Complete API architecture planning with documentation and CI/CD strategy',
    price_inr: 2999,
    duration_min: 60,
    duration: '1 hour',
    category: 'Enterprise',
    popular: false,
    features: ['Complete API architecture plan', 'Microservices decomposition', 'Event-driven design (Kafka)', 'CI/CD pipeline setup', 'Docker/K8s strategy', 'Detailed documentation', '7-day email support'],
  },
  {
    id: 'demo-s4',
    title: 'Full Stack Strategy',
    slug: 'full-stack-strategy',
    description: 'End-to-end architecture plan covering backend, mobile, cloud, and scaling',
    price_inr: 4999,
    duration_min: 90,
    duration: '90 min',
    category: 'Complete',
    popular: false,
    features: ['End-to-end architecture plan', 'Backend + Mobile strategy', 'AWS infrastructure design', 'Database selection & design', 'Security & auth patterns', 'Scaling roadmap', 'Tech stack decisions', '30-day email support'],
  },
];
